import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
  LineChart, Line
} from "recharts";
import { Banknote, TrendingUp, Users, Ship, ArrowUpRight } from "lucide-react";

// Mock data for charts
const revenueData = [
  { month: "Jan", exportFees: 4000, investorFees: 2400, other: 2400 },
  { month: "Feb", exportFees: 3000, investorFees: 1398, other: 2210 },
  { month: "Mar", exportFees: 2000, investorFees: 9800, other: 2290 },
  { month: "Apr", exportFees: 2780, investorFees: 3908, other: 2000 },
  { month: "May", exportFees: 1890, investorFees: 4800, other: 2181 },
  { month: "Jun", exportFees: 2390, investorFees: 3800, other: 2500 },
  { month: "Jul", exportFees: 3490, investorFees: 4300, other: 2100 },
];

const categoryData = [
  { name: "Sesame Export", value: 45000 },
  { name: "Hibiscus Export", value: 32000 },
  { name: "Land Leases", value: 15000 },
  { name: "Sandbox Access", value: 5000 },
];

const RevenueDashboard = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 pt-24 pb-12">
        {/* Header */}
        <div className="flex justify-between items-center mb-12">
          <div>
            <h1 className="text-4xl font-bold tracking-tight text-foreground">Revenue Simulation</h1>
            <p className="text-muted-foreground mt-2">Tracking state revenue generated by the AgTech platform.</p>
          </div>
          <Button size="lg" className="gap-2">
            <Banknote className="h-5 w-5" /> Simulate Payment
          </Button>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Total Revenue</CardTitle>
              <Banknote className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">₦97,000,000</div>
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <ArrowUpRight className="h-3 w-3 text-green-500" /> +20.1% from last month
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Export Levies</CardTitle>
              <Ship className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">₦77,000,000</div>
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <ArrowUpRight className="h-3 w-3 text-green-500" /> +15.5% from last month
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Investor Fees</CardTitle>
              <Users className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">₦15,000,000</div>
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <ArrowUpRight className="h-3 w-3 text-green-500" /> +5% from last month
              </p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium">Platform ROI</CardTitle>
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">12.4%</div>
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <ArrowUpRight className="h-3 w-3 text-green-500" /> +2.1% from last month
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
          {/* Revenue Over Time */}
          <Card>
            <CardHeader>
              <CardTitle>Revenue Growth</CardTitle>
              <CardDescription>Monthly revenue from export fees vs investor fees.</CardDescription>
            </CardHeader>
            <CardContent className="h-[300px]">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={revenueData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line type="monotone" dataKey="exportFees" stroke="#16a34a" name="Export Fees" />
                  <Line type="monotone" dataKey="investorFees" stroke="#2563eb" name="Investor Fees" />
                </LineChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          {/* Revenue by Category */}
          <Card>
            <CardHeader>
              <CardTitle>Revenue by Category</CardTitle>
              <CardDescription>Breakdown of total revenue generated.</CardDescription>
            </CardHeader>
            <CardContent className="h-[300px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={categoryData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="value" fill="#0d9488" name="Revenue (₦)" />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </div>

        {/* Recent Transactions (Simulated) */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Revenue Transactions</CardTitle>
            <CardDescription>Real-time log of payments processed by the platform.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {[
                { id: "TX123", desc: "Export Levy - 50 Bags of Sesame", amount: "₦25,000", status: "Paid", date: "Today" },
                { id: "TX124", desc: "Investor Application Fee", amount: "₦100,000", status: "Paid", date: "Yesterday" },
                { id: "TX125", desc: "Traceability QR Generation", amount: "₦5,000", status: "Paid", date: "2 days ago" },
                { id: "TX126", desc: "Export Levy - 100 Bags of Hibiscus", amount: "₦50,000", status: "Paid", date: "3 days ago" },
              ].map((tx) => (
                <div key={tx.id} className="flex justify-between items-center border-b pb-2 last:border-0 last:pb-0">
                  <div>
                    <p className="font-medium">{tx.desc}</p>
                    <p className="text-sm text-muted-foreground">{tx.id} • {tx.date}</p>
                  </div>
                  <div className="text-right">
                    <p className="font-bold text-green-600">{tx.amount}</p>
                    <p className="text-xs text-muted-foreground">{tx.status}</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </main>
      <Footer />
    </div>
  );
};

export default RevenueDashboard;
